export const TOGGLE_MUTED = 'TOGGLE_MUTED';
export const INIT_AUDIO_MANAGER_PENDING = 'INIT_AUDIO_MANAGER_PENDING';
export const INIT_AUDIO_MANAGER_SUCCESS = 'INIT_AUDIO_MANAGER_SUCCESS';
export const CREATE_INSTRUMENT = 'CREATE_INSTRUMENT';