export const TOGGLE_MUTED = 'TOGGLE_MUTED';
export const ADD_RACK = 'ADD_RACK';
export const REMOVE_RACK = 'REMOVE_RACK';
export const ADD_UNIT = 'ADD_UNIT';
export const ADD_NODE = 'ADD_NODE';
export const INIT_AUDIO_MANAGER_PENDING = 'INIT_AUDIO_MANAGER_PENDING';
export const INIT_AUDIO_MANAGER_SUCCESS = 'INIT_AUDIO_MANAGER_SUCCESS';